In [7]:
from google.colab import files
uploaded = files.upload()

Saving GlobalWeatherRepository.csv to GlobalWeatherRepository.csv

In [8]:
import pandas as pd

df = pd.read_csv('GlobalWeatherRepository.csv')

print("Dataset loaded successfully")
df.shape

Dataset loaded successfully

(122576, 41)

In [9]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [10]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122576 entries, 0 to 122575
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       122576 non-null  object
 1   location_name                 122576 non-null  object
 2   latitude                      122576 non-null  float64
 3   longitude                     122576 non-null  float64
 4   timezone                      122576 non-null  object
 5   last_updated_epoch            122576 non-null  int64
 6   last_updated                  122576 non-null  object
 7   temperature_celsius           122576 non-null  float64
 8   temperature_fahrenheit        122576 non-null  float64
 9   condition_text                122576 non-null  object
 10  wind_mph                      122576 non-null  float64
 11  wind_kph                      122576 non-null  float64
 12  wind_degree                   122576 non-null  int64
 13  wind_direction                122576 non-null  object
 14  pressure_mb                   122576 non-null  float64
 15  pressure_in                   122576 non-null  float64
 16  precip_mm                     122576 non-null  float64
 17  precip_in                     122576 non-null  float64
 18  humidity                      122576 non-null  int64
 19  cloud                         122576 non-null  int64
 20  feels_like_celsius            122576 non-null  float64
 21  feels_like_fahrenheit         122576 non-null  float64
 22  visibility_km                 122576 non-null  float64
 23  visibility_miles              122576 non-null  float64
 24  uv_index                      122576 non-null  float64
 25  gust_mph                      122576 non-null  float64
 26  gust_kph                      122576 non-null  float64
 27  air_quality_Carbon_Monoxide   122576 non-null  float64
 28  air_quality_Ozone             122576 non-null  float64
 29  air_quality_Nitrogen_dioxide  122576 non-null  float64
 30  air_quality_Sulphur_dioxide   122576 non-null  float64
 31  air_quality_PM2.5             122576 non-null  float64
 32  air_quality_PM10              122576 non-null  float64
 33  air_quality_us-epa-index      122576 non-null  int64
 34  air_quality_gb-defra-index    122576 non-null  int64
 35  sunrise                       122576 non-null  object
 36  sunset                        122576 non-null  object
 37  moonrise                      122576 non-null  object
 38  moonset                       122576 non-null  object
 39  moon_phase                    122576 non-null  object
 40  moon_illumination             122576 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 38.3+ MB

In [12]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,122576.000000,122576.000000,1.225760e+05,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,...,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000
mean,19.191038,21.996451,1.743124e+09,21.702574,71.066384,8.078715,13.004998,169.303012,1014.091470,29.945467,...,18.310804,479.760698,59.162055,15.315119,10.745007,24.694333,49.399417,1.713158,2.641643,49.932352
std,24.427963,65.792124,1.573369e+07,9.521555,17.138671,7.404669,11.913641,103.392391,10.649384,0.314438,...,14.044033,787.597532,31.217545,24.411940,37.249905,38.050908,152.348830,0.952670,2.478245,35.116175
min,-41.300000,-175.200000,1.715849e+09,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.729502e+09,16.300000,61.400000,4.000000,6.500000,81.000000,1010.000000,29.830000,...,10.400000,212.850000,39.000000,1.600000,1.050000,7.150000,10.100000,1.000000,1.000000,15.000000
50%,17.250000,23.316700,1.743155e+09,24.100000,75.400000,6.900000,11.200000,162.000000,1014.000000,29.930000,...,15.500000,305.250000,56.000000,5.400000,2.450000,14.350000,20.350000,1.000000,2.000000,50.000000
75%,40.400000,50.580000,1.756714e+09,28.100000,82.600000,11.200000,18.000000,256.000000,1018.000000,30.060000,...,24.300000,475.450000,75.000000,17.760000,8.695000,28.305000,42.365000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.770360e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

In [13]:
df.isnull().sum().sort_values(ascending=False)

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [15]:
df['last_updated'] = pd.to_datetime(df['last_updated'])

df['year'] = df['last_updated'].dt.year
df['month'] = df['last_updated'].dt.month
df['date'] = df['last_updated'].dt.date

In [16]:
import numpy as np

num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [17]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipython-input-3284995119.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [18]:
df.drop_duplicates(inplace=True)

df['country'] = df['country'].str.title()
df['location_name'] = df['location_name'].str.title()
df['condition_text'] = df['condition_text'].str.lower().str.strip()

In [19]:
drop_cols = [
    'temperature_fahrenheit',
    'wind_mph',
    'pressure_in',
    'precip_in'
]

df.drop(columns=drop_cols, inplace=True, errors='ignore')

In [20]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scale_cols = [
    'temperature_celsius',
    'humidity',
    'wind_kph',
    'air_quality_PM2.5',
    'air_quality_PM10'
]

df[scale_cols] = scaler.fit_transform(df[scale_cols])

In [21]:
monthly_df = df.groupby(
    ['country', 'location_name', 'year', 'month']
).agg({
    'temperature_celsius': 'mean',
    'humidity': 'mean',
    'air_quality_PM2.5': 'mean',
    'air_quality_PM10': 'mean'
}).reset_index()

In [22]:
df.to_csv("cleaned_weather_data.csv", index=False)
monthly_df.to_csv("monthly_weather_data.csv", index=False)

print("Preprocessed datasets saved successfully")

Preprocessed datasets saved successfully

In [23]:
from google.colab import files

files.download('cleaned_weather_data.csv')
files.download('monthly_weather_data.csv')

In [24]:
df.shape[1]

40

In [25]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'condition_text', 'wind_kph', 'wind_degree', 'wind_direction',
       'pressure_mb', 'precip_mm', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination',
       'year', 'month', 'date'],
      dtype='object')