In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/GlobalWeatherRepository.csv")
df.shape

(122576, 41)

In [2]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122576 entries, 0 to 122575
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       122576 non-null  object
 1   location_name                 122576 non-null  object
 2   latitude                      122576 non-null  float64
 3   longitude                     122576 non-null  float64
 4   timezone                      122576 non-null  object
 5   last_updated_epoch            122576 non-null  int64
 6   last_updated                  122576 non-null  object
 7   temperature_celsius           122576 non-null  float64
 8   temperature_fahrenheit        122576 non-null  float64
 9   condition_text                122576 non-null  object
 10  wind_mph                      122576 non-null  float64
 11  wind_kph                      122576 non-null  float64
 12  wind_degree                   122576 non-null  int64
 13  wind_direction                122576 non-null  object
 14  pressure_mb                   122576 non-null  float64
 15  pressure_in                   122576 non-null  float64
 16  precip_mm                     122576 non-null  float64
 17  precip_in                     122576 non-null  float64
 18  humidity                      122576 non-null  int64
 19  cloud                         122576 non-null  int64
 20  feels_like_celsius            122576 non-null  float64
 21  feels_like_fahrenheit         122576 non-null  float64
 22  visibility_km                 122576 non-null  float64
 23  visibility_miles              122576 non-null  float64
 24  uv_index                      122576 non-null  float64
 25  gust_mph                      122576 non-null  float64
 26  gust_kph                      122576 non-null  float64
 27  air_quality_Carbon_Monoxide   122576 non-null  float64
 28  air_quality_Ozone             122576 non-null  float64
 29  air_quality_Nitrogen_dioxide  122576 non-null  float64
 30  air_quality_Sulphur_dioxide   122576 non-null  float64
 31  air_quality_PM2.5             122576 non-null  float64
 32  air_quality_PM10              122576 non-null  float64
 33  air_quality_us-epa-index      122576 non-null  int64
 34  air_quality_gb-defra-index    122576 non-null  int64
 35  sunrise                       122576 non-null  object
 36  sunset                        122576 non-null  object
 37  moonrise                      122576 non-null  object
 38  moonset                       122576 non-null  object
 39  moon_phase                    122576 non-null  object
 40  moon_illumination             122576 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 38.3+ MB

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,122576.000000,122576.000000,1.225760e+05,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,...,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000
mean,19.191038,21.996451,1.743124e+09,21.702574,71.066384,8.078715,13.004998,169.303012,1014.091470,29.945467,...,18.310804,479.760698,59.162055,15.315119,10.745007,24.694333,49.399417,1.713158,2.641643,49.932352
std,24.427963,65.792124,1.573369e+07,9.521555,17.138671,7.404669,11.913641,103.392391,10.649384,0.314438,...,14.044033,787.597532,31.217545,24.411940,37.249905,38.050908,152.348830,0.952670,2.478245,35.116175
min,-41.300000,-175.200000,1.715849e+09,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.729502e+09,16.300000,61.400000,4.000000,6.500000,81.000000,1010.000000,29.830000,...,10.400000,212.850000,39.000000,1.600000,1.050000,7.150000,10.100000,1.000000,1.000000,15.000000
50%,17.250000,23.316700,1.743155e+09,24.100000,75.400000,6.900000,11.200000,162.000000,1014.000000,29.930000,...,15.500000,305.250000,56.000000,5.400000,2.450000,14.350000,20.350000,1.000000,2.000000,50.000000
75%,40.400000,50.580000,1.756714e+09,28.100000,82.600000,11.200000,18.000000,256.000000,1018.000000,30.060000,...,24.300000,475.450000,75.000000,17.760000,8.695000,28.305000,42.365000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.770360e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

In [3]:
df.duplicated().sum()

np.int64(0)

In [4]:
df['last_updated'] = pd.to_datetime(df['last_updated'])

In [6]:
df['year'] = df['last_updated'].dt.year
df['month'] = df['last_updated'].dt.month
df['day'] = df['last_updated'].dt.day
df['year_month'] = df['last_updated'].dt.to_period('M')

In [7]:
print("Duplicates:", df.duplicated().sum())
df = df.drop_duplicates()

Duplicates: 0

In [8]:
df[['wind_kph', 'gust_kph', 'pressure_mb']].describe()

            wind_kph       gust_kph    pressure_mb
count  122576.000000  122576.000000  122576.000000
mean       13.004998      18.310804    1014.091470
std        11.913641      14.044033      10.649384
min         3.600000       3.600000     947.000000
25%         6.500000      10.400000    1010.000000
50%        11.200000      15.500000    1014.000000
75%        18.000000      24.300000    1018.000000
max      2963.200000    2970.400000    3006.000000

In [9]:
import numpy as np

df.loc[df['wind_kph'] > 200, 'wind_kph'] = np.nan
df.loc[df['gust_kph'] > 250, 'gust_kph'] = np.nan
df.loc[df['pressure_mb'] > 1100, 'pressure_mb'] = np.nan
df.loc[df['pressure_mb'] < 900, 'pressure_mb'] = np.nan

In [10]:
air_cols = [
    'air_quality_Carbon_Monoxide',
    'air_quality_Ozone',
    'air_quality_Nitrogen_dioxide',
    'air_quality_Sulphur_dioxide',
    'air_quality_PM2.5',
    'air_quality_PM10'
]

for col in air_cols:
    df.loc[df[col] < 0, col] = np.nan

In [11]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        4
wind_degree                     0
wind_direction                  0
pressure_mb                     2
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        3
air_quality_Carbon_Monoxide     1
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     1
air_quality_PM2.5               0
air_quality_PM10                2
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
year                            0
month                           0
year_month                      0
day                             0
dtype: int64

In [12]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [13]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
year                            0
month                           0
year_month                      0
day                             0
dtype: int64

In [14]:
selected_columns = [
    'country',
    'location_name',
    'latitude',
    'longitude',
    'last_updated',
    'year',
    'month',
    'temperature_celsius',
    'feels_like_celsius',
    'humidity',
    'wind_kph',
    'gust_kph',
    'pressure_mb',
    'precip_mm',
    'uv_index',
    'cloud',
    'visibility_km',
    'air_quality_PM2.5',
    'air_quality_PM10'
]

df = df[selected_columns]

In [17]:
print(df.columns)

Index(['country', 'location_name', 'latitude', 'longitude', 'last_updated',
       'year', 'month', 'temperature_celsius', 'feels_like_celsius',
       'humidity', 'wind_kph', 'gust_kph', 'pressure_mb', 'precip_mm',
       'uv_index', 'cloud', 'visibility_km', 'air_quality_PM2.5',
       'air_quality_PM10'],
      dtype='object')

In [18]:
df['last_updated'] = pd.to_datetime(df['last_updated'])
df['year_month'] = df['last_updated'].dt.to_period('M')

In [19]:
df['last_updated'] = pd.to_datetime(df['last_updated'])

df['year'] = df['last_updated'].dt.year
df['month'] = df['last_updated'].dt.month
df['year_month'] = df['last_updated'].dt.to_period('M')

In [20]:
df[['last_updated','year_month']].head()

         last_updated year_month
0 2024-05-16 13:15:00    2024-05
1 2024-05-16 10:45:00    2024-05
2 2024-05-16 09:45:00    2024-05
3 2024-05-16 10:45:00    2024-05
4 2024-05-16 09:45:00    2024-05

In [21]:
monthly_avg = df.groupby(['country','year_month']).mean(numeric_only=True).reset_index()

In [23]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'last_updated',
       'year', 'month', 'temperature_celsius', 'feels_like_celsius',
       'humidity', 'wind_kph', 'gust_kph', 'pressure_mb', 'precip_mm',
       'uv_index', 'cloud', 'visibility_km', 'air_quality_PM2.5',
       'air_quality_PM10', 'year_month'],
      dtype='object')

In [24]:
df.to_csv("../data/processed/weather_cleaned_daily.csv", index=False)
monthly_avg.to_csv("../data/processed/weather_cleaned_monthly.csv", index=False)

In [26]:
df.to_csv("../data/processed/weather_cleaned_daily.csv", index=False)
monthly_avg.to_csv("../data/processed/weather_cleaned_monthly.csv", index=False)

In [28]:
df.shape

(122576, 20)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122576 entries, 0 to 122575
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   country              122576 non-null  object
 1   location_name        122576 non-null  object
 2   latitude             122576 non-null  float64
 3   longitude            122576 non-null  float64
 4   last_updated         122576 non-null  datetime64[ns]
 5   year                 122576 non-null  int32
 6   month                122576 non-null  int32
 7   temperature_celsius  122576 non-null  float64
 8   feels_like_celsius   122576 non-null  float64
 9   humidity             122576 non-null  int64
 10  wind_kph             122576 non-null  float64
 11  gust_kph             122576 non-null  float64
 12  pressure_mb          122576 non-null  float64
 13  precip_mm            122576 non-null  float64
 14  uv_index             122576 non-null  float64
 15  cloud                122576 non-null  int64
 16  visibility_km        122576 non-null  float64
 17  air_quality_PM2.5    122576 non-null  float64
 18  air_quality_PM10     122576 non-null  float64
 19  year_month           122576 non-null  period[M]
dtypes: datetime64[ns](1), float64(12), int32(2), int64(2), object(2), period[M](1)
memory usage: 17.8+ MB

In [30]:
df.describe()

,latitude,longitude,last_updated,year,month,temperature_celsius,feels_like_celsius,humidity,wind_kph,gust_kph,pressure_mb,precip_mm,uv_index,cloud,visibility_km,air_quality_PM2.5,air_quality_PM10
count,122576.000000,122576.000000,122576,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000,122576.000000
mean,19.191038,21.996451,2025-03-28 03:11:52.644400384,2024.694377,7.021187,21.702574,22.613045,66.006380,12.975177,18.282501,1014.059016,0.137373,3.474084,39.997601,9.526798,24.694333,49.422969
min,-41.300000,-175.200000,2024-05-16 01:45:00,2024.000000,1.000000,-29.800000,-36.700000,2.000000,3.600000,3.600000,947.000000,0.000000,0.000000,0.000000,0.000000,0.168000,0.168000
25%,3.750000,-6.836100,2024-10-21 14:37:30,2024.000000,5.000000,16.300000,16.300000,50.000000,6.500000,10.400000,1010.000000,0.000000,0.200000,0.000000,10.000000,7.150000,10.136000
50%,17.250000,23.316700,2025-03-28 11:30:00,2025.000000,7.000000,24.100000,25.400000,71.000000,11.200000,15.500000,1014.000000,0.000000,2.200000,30.500000,10.000000,14.350000,20.350000
75%,40.400000,50.580000,2025-09-01 12:15:00,2025.000000,10.000000,28.100000,30.200000,84.000000,18.000000,24.300000,1018.000000,0.030000,6.000000,75.000000,10.000000,28.305000,42.365000
max,64.150000,179.220000,2026-02-06 19:45:00,2026.000000,12.000000,49.200000,51.200000,100.000000,172.100000,213.100000,1080.000000,42.240000,16.300000,100.000000,32.000000,1614.100000,6037.290000
std,24.427963,65.792124,NaN,0.571445,3.435444,9.521555,11.378903,24.033528,8.341630,11.183902,6.990272,0.574064,3.569382,34.054907,2.661347,38.050908,152.223031

In [31]:
df.head()

,country,location_name,latitude,longitude,last_updated,year,month,temperature_celsius,feels_like_celsius,humidity,wind_kph,gust_kph,pressure_mb,precip_mm,uv_index,cloud,visibility_km,air_quality_PM2.5,air_quality_PM10,year_month
0,Afghanistan,Kabul,34.52,69.18,2024-05-16 13:15:00,2024,5,26.6,25.3,24,13.3,15.3,1012.0,0.0,7.0,30,10.0,8.4,26.6,2024-05
1,Albania,Tirana,41.33,19.82,2024-05-16 10:45:00,2024,5,19.0,19.0,94,11.2,18.4,1012.0,0.1,5.0,75,10.0,1.1,2.0,2024-05
2,Algeria,Algiers,36.76,3.05,2024-05-16 09:45:00,2024,5,23.0,24.6,29,15.1,22.3,1011.0,0.0,5.0,0,10.0,10.4,18.4,2024-05
3,Andorra,Andorra La Vella,42.50,1.52,2024-05-16 10:45:00,2024,5,6.3,3.8,61,11.9,13.7,1007.0,0.3,2.0,100,2.0,0.7,0.9,2024-05
4,Angola,Luanda,-8.84,13.23,2024-05-16 09:45:00,2024,5,26.0,28.7,89,13.0,20.2,1011.0,0.0,8.0,50,10.0,183.4,262.3,2024-05